import { Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Quiz App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        style={poppins.style}
        className='min-h-screen bg-gradient-to-tr from-indigo-900 to-fuchsia-900 text-white'
      >
        {children}
      </body>
    </html>
  )
}
